package gui.process;

import client.network.NetworkService;
import gui.MainApplication;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.HashMap;
import java.util.Map;

/**
 * Service class to handle non-UI logic and test data generation.
 * This helps maintain a clean MVC architecture by separating business/test logic from the UI controllers.
 */
public class UIService {
    private static final Logger log = LoggerFactory.getLogger(UIService.class);

    /**
     * Generates and sends a dummy auction creation request for testing purposes.
     */
    public static void createTestAuction() {
        String testItemName = "TEST_ITEM_" + (System.currentTimeMillis() % 10000);
        Map<String, String> dummyData = new HashMap<>();
        dummyData.put("itemName", testItemName);
        dummyData.put("description", "Test description generated by UIService");
        dummyData.put("startingPrice", "50000");
        dummyData.put("bidIncrement", "5000");
        dummyData.put("durationMinutes", "60");

        log.debug("UIService: Sending CREATE_AUCTION for {}", testItemName);
        NetworkService.sendMessage("CREATE_AUCTION", dummyData);
    }

    /**
     * Handles specialized "fun" or Easter egg logic to keep the UI controller clean.
     *
     * @param clickCount The current number of clicks to evaluate.
     * @return The updated click count or 0 if reset.
     */
    public static int handleAccountTrollLogic(int clickCount) {
        if (clickCount == 67) {
            try {
                String trollUrl = "https://www.tiktok.com/@rven6166/video/7615455293991963934";
                if (java.awt.Desktop.isDesktopSupported() && java.awt.Desktop.getDesktop().isSupported(java.awt.Desktop.Action.BROWSE)) {
                    java.awt.Desktop.getDesktop().browse(new java.net.URI(trollUrl));
                }
            } catch (Exception e) {
                log.error("Easter egg error: {}", e.getMessage());
            }
            return 0; // Reset count
        }
        return clickCount;
    }
}
