serverPort=6969
serverURL=https://webhook.site/a1a4fa22-525c-4c3e-9065-e9814e5b95a9
# For automated IP - PORT
binID=69d4960b856a6821890813a2

# Contingency
fallbackServerURL=localhost
fallbackServerPort=6969